/*
 * Project:         Java II (COP 2805) Search Engine
 * Team:            Super Friends
 * Authors:         Jon Davidson
 *                  Thanh J. Duong A.K.A. Chino Caliente
 *                  John McLain
 *                  Shaz Hosein        
 *
 * Date Started:    January 29th, 2014
 */

package superfriends;

import java.util.*;
import javax.swing.*;

/**
 * @author Jon Davidson
 * @author Chino Caliente
 * @author John McLain
 * @author Shaz Hosein
 */

public class Main extends JFrame {
    public static void main(String args[]) {
        
        // applies the native system's look-and-feel to the UI
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } 
        catch (     ClassNotFoundException | 
                    InstantiationException | 
                    IllegalAccessException | 
                    UnsupportedLookAndFeelException ex) {
            System.out.println("Unable to load native look and feel");
        }
        
        // instantiates and shows the main JFrame
        new Main().setVisible(true);
    }

    /**
     * Creates new form NewJFrame
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSearchTerms = new javax.swing.ButtonGroup();
        jLabelTitle = new javax.swing.JLabel();
        jLabelSearchTerms = new javax.swing.JLabel();
        jButtonSearch = new javax.swing.JButton();
        jTextFieldSearchTerms = new javax.swing.JTextField();
        jRadioButtonAny = new javax.swing.JRadioButton();
        jRadioButtonExact = new javax.swing.JRadioButton();
        jRadioButtonAll = new javax.swing.JRadioButton();
        jPanelResults = new javax.swing.JPanel();
        jScrollPaneResults = new javax.swing.JScrollPane();
        jTextAreaResults = new javax.swing.JTextArea();
        jButtonMaintenance = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jButtonAbout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Superfriends Search Engine");
        setBackground(java.awt.SystemColor.window);

        jLabelTitle.setFont(jLabelTitle.getFont().deriveFont(jLabelTitle.getFont().getStyle() | java.awt.Font.BOLD, jLabelTitle.getFont().getSize()+3));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Superfriends Search Engine");

        jLabelSearchTerms.setFont(jLabelSearchTerms.getFont().deriveFont(jLabelSearchTerms.getFont().getStyle() | java.awt.Font.BOLD));
        jLabelSearchTerms.setText("Search Terms:");

        jButtonSearch.setFont(jButtonSearch.getFont());
        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jTextFieldSearchTerms.setFont(jTextFieldSearchTerms.getFont());

        buttonGroupSearchTerms.add(jRadioButtonAny);
        jRadioButtonAny.setFont(jRadioButtonAny.getFont());
        jRadioButtonAny.setText("Any of the Terms");
        jRadioButtonAny.setEnabled(false);

        buttonGroupSearchTerms.add(jRadioButtonExact);
        jRadioButtonExact.setFont(jRadioButtonExact.getFont());
        jRadioButtonExact.setText("Exact Phrase");
        jRadioButtonExact.setEnabled(false);

        buttonGroupSearchTerms.add(jRadioButtonAll);
        jRadioButtonAll.setFont(jRadioButtonAll.getFont());
        jRadioButtonAll.setText("All of the Terms");
        jRadioButtonAll.setEnabled(false);

        jPanelResults.setBorder(javax.swing.BorderFactory.createTitledBorder("Matching Results"));

        jTextAreaResults.setColumns(20);
        jTextAreaResults.setFont(jTextAreaResults.getFont());
        jTextAreaResults.setRows(5);
        jTextAreaResults.setText("C:\\SearchResults\\WillAppear\\RightHere.txt");
        jTextAreaResults.setFocusable(false);
        jScrollPaneResults.setViewportView(jTextAreaResults);

        javax.swing.GroupLayout jPanelResultsLayout = new javax.swing.GroupLayout(jPanelResults);
        jPanelResults.setLayout(jPanelResultsLayout);
        jPanelResultsLayout.setHorizontalGroup(
            jPanelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneResults)
                .addContainerGap())
        );
        jPanelResultsLayout.setVerticalGroup(
            jPanelResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneResults, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonMaintenance.setFont(jButtonMaintenance.getFont());
        jButtonMaintenance.setLabel("Maintenance");
        jButtonMaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMaintenanceActionPerformed(evt);
            }
        });

        jButtonClose.setFont(jButtonClose.getFont());
        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jButtonAbout.setFont(jButtonAbout.getFont());
        jButtonAbout.setText("About");
        jButtonAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAboutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addComponent(jPanelResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSearchTerms)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSearchTerms)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jRadioButtonAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonAny)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonExact)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonMaintenance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAbout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClose)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSearchTerms, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelSearchTerms)
                        .addComponent(jButtonSearch)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonAny)
                    .addComponent(jRadioButtonExact)
                    .addComponent(jRadioButtonAll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMaintenance)
                    .addComponent(jButtonClose)
                    .addComponent(jButtonAbout))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        // Close the program
        System.exit(0);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMaintenanceActionPerformed
        // Open the maintenance window
        new Maintenance().setVisible(true);
    }//GEN-LAST:event_jButtonMaintenanceActionPerformed

    /*
    What happens when you actually press the Search button!
    */
    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        
        String search = jTextFieldSearchTerms.getText();
        
        List<String> results = Search.Query( search );
        Iterator<String> iterator = results.iterator();
        
        StringBuilder sb = new StringBuilder();
        
        while ( iterator.hasNext() ) {
            sb.append( iterator.next() );
            sb.append( "\n" );
        }
        
        jTextAreaResults.setText( sb.toString() );
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jButtonAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAboutActionPerformed
        JOptionPane.showMessageDialog(null, "Some Superfriends made this.");
    }//GEN-LAST:event_jButtonAboutActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSearchTerms;
    private javax.swing.JButton jButtonAbout;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonMaintenance;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabelSearchTerms;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanelResults;
    private javax.swing.JRadioButton jRadioButtonAll;
    private javax.swing.JRadioButton jRadioButtonAny;
    private javax.swing.JRadioButton jRadioButtonExact;
    private javax.swing.JScrollPane jScrollPaneResults;
    private javax.swing.JTextArea jTextAreaResults;
    private javax.swing.JTextField jTextFieldSearchTerms;
    // End of variables declaration//GEN-END:variables
}
